/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import Model.Cardset;

import javax.swing.JOptionPane;
/**
 *
 * @author ignac
 */
public class CrearMazo extends javax.swing.JFrame {

    private Integer numE;
    private Integer numC;
    private ArrayList<String> simbolos;
    public static Cardset mazo;
    public CrearMazo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        getE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        getC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        getsimbolos = new javax.swing.JTextField();
        Ingresarparametos = new javax.swing.JButton();
        Entreamigos = new javax.swing.JButton();
        Ayudaprimo = new javax.swing.JButton();
        ayudacartas = new javax.swing.JButton();
        ayudasimbolos = new javax.swing.JButton();
        Vermazo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(137, 221, 240));

        jLabel1.setText("¿Cuántos simbolos quiere en cada carta?");

        jLabel2.setText("¿Cuántas cartas quiere que tenga el mazo?");

        jLabel3.setText("Ingrese los simbolos que quiere en las cartas");

        getsimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getsimbolosActionPerformed(evt);
            }
        });

        Ingresarparametos.setText("Crear mazo!!");
        Ingresarparametos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarparametosActionPerformed(evt);
            }
        });

        Entreamigos.setText("Jugar entre amigos");
        Entreamigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreamigosActionPerformed(evt);
            }
        });

        Ayudaprimo.setText("?");
        Ayudaprimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaprimoActionPerformed(evt);
            }
        });

        ayudacartas.setText("?");
        ayudacartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudacartasActionPerformed(evt);
            }
        });

        ayudasimbolos.setText("?");
        ayudasimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudasimbolosActionPerformed(evt);
            }
        });

        Vermazo.setText("Ver mazo");
        Vermazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VermazoActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/solomanito.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(getsimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getC, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getE, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ayudaprimo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayudacartas)
                    .addComponent(ayudasimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Vermazo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(Ingresarparametos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Entreamigos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ayudaprimo))
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayudacartas))
                .addGap(44, 44, 44)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getsimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayudasimbolos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ingresarparametos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vermazo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Entreamigos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getsimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getsimbolosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getsimbolosActionPerformed

    private void IngresarparametosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarparametosActionPerformed
        // TODO add your handling code here:
        this.simbolos = new ArrayList<>();
        this.simbolos.add(" ");
        this.numE = Integer.valueOf(getE.getText());
        Integer maxCartas = ((numE -1)*(numE -1)) + (numE -1) + 1;
        this.numC = Integer.valueOf(getC.getText());
        String simbolo = getsimbolos.getText();
        String[] ss = simbolo.split(" ");

        for(Integer i = 0; i < maxCartas ; i++){
            this.simbolos.add(ss[i]);
        }

        mazo = new Cardset(numE, numC, simbolos);
        if(!(mazo.isdobble())){
            JOptionPane.showMessageDialog(null, "El mazo no es válido\n Tienen que ingresar un numero primo y simbolos que no se repitan");
            mazo = null;
        }
       
        
    }//GEN-LAST:event_IngresarparametosActionPerformed

    private void VermazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VermazoActionPerformed
        JOptionPane.showMessageDialog(null, "Su mazo es: \n" + mazo.cardset_string());
    }//GEN-LAST:event_VermazoActionPerformed

    private void EntreamigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreamigosActionPerformed
        
        CrearGame creargame = new CrearGame();
        creargame.setVisible(true);
        this.setVisible(false);
       
      
    }//GEN-LAST:event_EntreamigosActionPerformed

    private void AyudaprimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaprimoActionPerformed
        JOptionPane.showMessageDialog(null, "Tiene que ser un número primo más 1\n Ejemplo 3(primo) + 1 = 4 número valido");
    }//GEN-LAST:event_AyudaprimoActionPerformed

    private void ayudacartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudacartasActionPerformed
        this.numE = Integer.valueOf(getE.getText());
        Integer e = this.numE-1;
        Integer maxcartas = e*e + e +1;
        JOptionPane.showMessageDialog(null, "Pueden ser máximo " + maxcartas.toString()+" cartas\n Puede ingresar -1 y obtendrá el total de las cartas");
    }//GEN-LAST:event_ayudacartasActionPerformed

    private void ayudasimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudasimbolosActionPerformed
        this.numE = Integer.valueOf(getE.getText());
        Integer e = this.numE-1;
        Integer maxcartas = e*e + e +1;
        JOptionPane.showMessageDialog(null, "Tienen que ser como mínimo"+ maxcartas.toString()+ " simbolos, además todos deben ser diferente");
    }//GEN-LAST:event_ayudasimbolosActionPerformed

 
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayudaprimo;
    private javax.swing.JButton Entreamigos;
    private javax.swing.JButton Ingresarparametos;
    private javax.swing.JButton Vermazo;
    private javax.swing.JButton ayudacartas;
    private javax.swing.JButton ayudasimbolos;
    private javax.swing.JTextField getC;
    private javax.swing.JTextField getE;
    private javax.swing.JTextField getsimbolos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
