/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import Model.Cardset;
import javax.swing.JOptionPane;
/**
 *
 * @author ignac
 */
public class CrearMazo extends javax.swing.JFrame {

    private Integer numE;
    private Integer numC;
    private ArrayList<String> simbolos = new ArrayList<>();
    public static Cardset mazo;
    public CrearMazo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        getC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        getsimbolos = new javax.swing.JTextField();
        Ingresarparametos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        getE = new javax.swing.JTextField();
        Vermazo = new javax.swing.JButton();
        Entreamigos = new javax.swing.JButton();
        vscpu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("¿Cuántas cartas quiere que tenga el mazo?");

        jLabel3.setText("Ingrese los simbolos que quiere en las cartas");

        getsimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getsimbolosActionPerformed(evt);
            }
        });

        Ingresarparametos.setText("Crear mazo!!");
        Ingresarparametos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarparametosActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Cuántos simbolos quiere en cada carta?");

        Vermazo.setText("Ver mazo");
        Vermazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VermazoActionPerformed(evt);
            }
        });

        Entreamigos.setText("Jugar entre amigos");
        Entreamigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreamigosActionPerformed(evt);
            }
        });

        vscpu.setText("Contra la cpu");
        vscpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vscpuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(getE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(getC)
                                .addComponent(getsimbolos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(Ingresarparametos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Vermazo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(Entreamigos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(vscpu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getsimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ingresarparametos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vermazo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entreamigos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vscpu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getsimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getsimbolosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getsimbolosActionPerformed

    private void IngresarparametosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarparametosActionPerformed
        // TODO add your handling code here:
        this.simbolos.add(" ");
        this.numE = Integer.valueOf(getE.getText());
        Integer maxCartas = ((numE -1)*(numE -1)) + (numE -1) + 1;
        this.numC = Integer.valueOf(getC.getText());
        String simbolo = getsimbolos.getText();
        String[] ss = simbolo.split(" ");

        for(Integer i = 0; i < maxCartas ; i++){
            this.simbolos.add(ss[i]);
        }

        mazo = new Cardset(numE, numC, simbolos);
        
    }//GEN-LAST:event_IngresarparametosActionPerformed

    private void VermazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VermazoActionPerformed
        JOptionPane.showMessageDialog(null, "Su mazo es: \n" + mazo.cardset_string());
    }//GEN-LAST:event_VermazoActionPerformed

    private void EntreamigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreamigosActionPerformed
        
        CrearGame creargame = new CrearGame();
        creargame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EntreamigosActionPerformed

 
    
    
    private void vscpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vscpuActionPerformed
        Contracpu contracpu = new Contracpu();
        contracpu.setVisible(true);
    }//GEN-LAST:event_vscpuActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entreamigos;
    private javax.swing.JButton Ingresarparametos;
    private javax.swing.JButton Vermazo;
    private javax.swing.JTextField getC;
    private javax.swing.JTextField getE;
    private javax.swing.JTextField getsimbolos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton vscpu;
    // End of variables declaration//GEN-END:variables
}
